# Generated by Django 2.2.6 on 2019-10-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abitura',
            name='name',
        ),
        migrations.AddField(
            model_name='abitura',
            name='text',
            field=models.TextField(default=1, max_length=122),
            preserve_default=False,
        ),
    ]
