# Generated by Django 2.2.6 on 2019-10-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_teacher_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default=True, upload_to='personal/media/img/'),
        ),
    ]
