# Generated by Django 2.2.6 on 2019-10-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_auto_20191030_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='description',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
