# Generated by Django 2.2.6 on 2019-10-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_auto_20191030_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='description',
            field=models.TextField(blank=True, max_length=11500, null=True),
        ),
    ]
